server:
  port: 8080

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
        # Security Service - All public
        - id: security-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=1

        # Catalog Service - Public product browsing
        - id: catalog-service-public
          uri: http://localhost:8082
          predicates:
            - Path=/api/catalog/products/**, /api/catalog/categories/**
          filters:
            - StripPrefix=1

        # Catalog Service - Admin only (product management)
        - id: catalog-service-admin
          uri: http://localhost:8082
          predicates:
            - Path=/api/catalog/admin/**
          filters:
            - StripPrefix=1
            - name: AuthenticationFilter
            - name: RoleBasedAuthorizationFilter
              args:
                required-roles: ADMIN

        # Order Service - User access (own orders only)
        - id: order-service-user
          uri: http://localhost:8083
          predicates:
            - Path=/api/orders/**
          filters:
            - StripPrefix=1
            - name: AuthenticationFilter
            - name: RoleBasedAuthorizationFilter
              args:
                required-roles: USER,CUSTOMER

        # Order Service - Admin access (all orders)
        - id: order-service-admin
          uri: http://localhost:8083
          predicates:
            - Path=/api/orders/admin/**
          filters:
            - StripPrefix=1
            - name: AuthenticationFilter
            - name: RoleBasedAuthorizationFilter
              args:
                required-roles: ADMIN

        # Cart Service - Authenticated users only
        - id: cart-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/cart/**
          filters:
            - StripPrefix=1
            - name: AuthenticationFilter
            - name: RoleBasedAuthorizationFilter
              args:
                required-roles: USER,CUSTOMER

      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
        - AddResponseHeader=Access-Control-Allow-Origin, *
        - AddResponseHeader=Access-Control-Allow-Methods, GET,POST,PUT,DELETE,OPTIONS
        - AddResponseHeader=Access-Control-Allow-Headers, *
        - AddResponseHeader=Access-Control-Max-Age, 3600

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8081/auth/.well-known/jwks.json

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.security: DEBUG
    com.ecommerce.gateway: DEBUG
